### ISSUE TITLE
wildcard with relational operator deprecation message

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/poetry-plugin-tweak-dependencies-version-feedstock#4]
### Comment:

Hi @bollwyvl

It appears that using 
    - poetry ==1.6.*
https://github.com/conda-forge/poetry-plugin-tweak-dependencies-version-feedstock/blob/41964f0475322f18f3f679131b0be341600e43c4/recipe/meta.yaml#L24C4-L24C21

Is a possible cause of 
```WARNING conda.models.version:get_matcher(546): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0```

Here is what I could find on the issue, but it seems hard to figure out which package is the  cause of this warning. 
https://github.com/conda/conda/issues/9140

Do you think it warrants changing the recipe to 

poetry >=1.6.0,<1.7.0 or similar. 

Thank you and Regards.

**Comment by bollwyvl** [comment]
Yep, opened #5, will check the logs and merge when :heavy_check_mark: .

I've found the "future" is often "well, we can't, because customer x..."  (see use of md5 in 2023) with some of the `conda` deprecation messages, but no reason to tempt fate. I probably _won't_ bother going back and doing a repodata patch, but _someone_ could...

As to this specific operator: the generated `METADATA` in the upstream wheel keeps that syntax instead of normalizing as it does for `~` and `^` (with different semantics than _other_ systems), but it doesn't fail vs `pip check` with poetry `1.6.1`... so I guess we just chalk it up to another "why we can't have nice things" between `conda` and `pip` (and every other clever system) version spec operators.

**Comment by bollwyvl** [comment]
Merged that, should be up after https://github.com/conda-forge/poetry-plugin-tweak-dependencies-version-feedstock/runs/16717768893 (and the CDN delay).

If you get a chance to test, and still see that error from this package, feel free to re-open. Thanks for the report.
